set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Keep Plugin commands between vundle#begin/end.

" Syntastic
Plugin 'scrooloose/syntastic'
" Tagbar
" requires exuberant-ctags
Plugin 'majutsushi/tagbar'

if v:version > 703
    " YouCompleteMe
    " Only supported from v7.3.598
    Plugin 'Valloric/YouCompleteMe'
else
    " SuperTab
    Plugin 'vim-scripts/supertab'
endif
" Switch between c source and headers
Plugin 'vim-scripts/a.vim'
" Line diff
Plugin 'AndrewRadev/linediff.vim'
" Tab merge
Plugin 'vim-scripts/Tabmerge'
" Markdown previewer
Plugin 'suan/vim-instant-markdown'
" Provide jade syntax highlighting
Plugin 'digitaltoad/vim-jade'
" Provide stylus syntax highlighting
Plugin 'wavded/vim-stylus'
" Git plugin
Plugin 'tpope/vim-fugitive'
" Surround
Plugin 'tpope/vim-surround'
" Consistent configurations between editors
Plugin 'editorconfig/editorconfig-vim'
" Typescript syntax
Plugin 'leafgarland/typescript-vim'
" Async!
Plugin 'tpope/vim-dispatch'
" Git status
Plugin 'airblade/vim-gitgutter'
" 'Safe' environment for editing code blocks
Plugin 'ferranpm/vim-isolate'
" DBMS interface
Plugin 'cosminadrianpopescu/vim-sql-workbench'
" Fuzzy finder
Plugin 'kien/ctrlp.vim'
" Silver searcher
Plugin 'rking/ag.vim'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" .vimrc
set showmode
set showcmd
set title
set number
set mouse=a
set backspace=2
set showmatch
set ruler

set expandtab
set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set shiftround
set autoindent
set smartindent
set hlsearch

set splitright
set splitbelow

set colorcolumn=80

set spelllang=en_gb
autocmd FileType tex,bib,plaintex,markdown set spell

autocmd FileType c,h,cpp,hpp,cc setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType ruby setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Prevent tabexpand in Makefiles
au BufNewFile,BufRead Makefile set noexpandtab

"highlight WhitespaceEOL ctermbg=yellow guibg=red
"match WhitespaceEOL /\s\+$/
"autocmd ColorScheme * highlight WhitespaceEOL ctermbg=red guibg=red

highlight ExtraWhitespace ctermbg=red guibg=red
augroup extra_whitespace
    autocmd!
    autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
    autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
augroup END

syntax on
let &t_Co=256
colorscheme jellybeans

" Use x11 clipboard
if has('xterm_clipboard')
    if version >= 730
        set clipboard=unnamedplus
    else
        noremap Y "+Y
        noremap y "+y
        noremap yy "+yy
        noremap c "+c
        noremap C "+C
        noremap d "+d
        nnoremap dd "+dd
        noremap p "+p
        noremap P "+P
        noremap r "+r
        noremap R "+R
        noremap c "+c
        noremap C "+C
        noremap cc "+cc
    endif
endif

" Disable arrows
noremap <left> <nop>
noremap <right> <nop>
noremap <up> <nop>
noremap <down> <nop>

let mapleader = "-"

" $VIMRC Editing

nnoremap <leader>ev :tabnew $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Reload the source when writing to $MYVIMRC
augroup reload_source
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END
