set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Keep Plugin commands between vundle#begin/end.

" Syntastic
Plugin 'scrooloose/syntastic'
" Tagbar
" requires exuberant-ctags
Plugin 'majutsushi/tagbar'
" SuperTab
Plugin 'vim-scripts/supertab'
" Switch between c source and headers
Plugin 'vim-scripts/a.vim'
" Line diff
Plugin 'AndrewRadev/linediff.vim'
" Tab merge
Plugin 'vim-scripts/Tabmerge'
" Markdown previewer
Plugin 'suan/vim-instant-markdown'
" Provide jade syntax highlighting
Plugin 'digitaltoad/vim-jade'
" Provide stylus syntax highlighting
Plugin 'wavded/vim-stylus'
" Git plugin
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" .vimrc
set showmode
set showcmd
set title
set number
set mouse=a
set backspace=2
set showmatch
set ruler

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set hlsearch

set colorcolumn=80

set spelllang=en_gb
autocmd FileType tex,bib,plaintex,markdown set spell

autocmd FileType c,h,cpp,hpp,cc setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType ruby setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

au BufNewFile,BufRead *.soy set filetype=html
au BufNewFile,BufRead *.md set filetype=markdown

" Prevent tabexpand in Makefiles
au BufNewFile,BufRead Makefile set noexpandtab

"highlight WhitespaceEOL ctermbg=yellow guibg=red
"match WhitespaceEOL /\s\+$/
"autocmd ColorScheme * highlight WhitespaceEOL ctermbg=red guibg=red

highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/

"highlight WhitespaceEOL ctermbg=yellow guibg=red
"match WhitespaceEOL /\s\+$/
"autocmd ColorScheme * highlight WhitespaceEOL ctermbg=red guibg=red

highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/

syntax on
colorscheme jellybeans

" Use x11 clipboard
if has('xterm_clipboard')
    if version >= 730
        set clipboard=unnamedplus
    else
        noremap Y "+Y
        noremap y "+y
        noremap yy "+yy
        noremap c "+c
        noremap C "+C
        noremap d "+d
        nnoremap dd "+dd
        noremap p "+p
        noremap P "+P
        noremap r "+r
        noremap R "+R
        noremap c "+c
        noremap C "+C
        noremap cc "+cc
    endif
endif
