if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

if [ -f $HOME/Documents/Development/dotfiles/tmux/tmux_completion ]; then
    . $HOME/Documents/Development/dotfiles/tmux/tmux_completion
fi

export GOPATH="$HOME/Documents/Development/go"

KANO_BASE="$HOME/Documents/Development/Kano"
KANO_PACKAGES="kano-applets
               kano-settings
               make-light
               kano-blocks
               make-pong
               make-minecraft
               kano-toolset
               kano-peripherals
               kano-widgets
               kano-profile"

for PKG in $KANO_PACKAGES; do
    export PYTHONPATH="$PYTHONPATH:$KANO_BASE/$PKG"
done

# alias docker-init="eval \'$(docker-machine env default)\'"
alias docker-init="docker-machine env default"

# Rust
source $HOME/.cargo/env
